apiVersion: v2
name: gp-hub-monitoring
description: A Helm chart for deploying a Metrics Monitoring Stack on our Hub-Cluster

type: application

version: 0.11.0

dependencies:
  - name: mimir-distributed
    alias: mimir
    version: 4.3.0
    repository: https://grafana.github.io/helm-charts
  - name: grafana
    version: 6.54.0
    repository: https://grafana.github.io/helm-charts
  - name: kube-state-metrics
    version: 5.5.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: test-chart
    version: 0.2.0
    repository: https://tomeindl.github.io/renovate-test-dep/
