apiVersion: v2
name: gp-cluster-logging-instance
description: A Helm chart for Kubernetes

type: application
version: 2.9.0

dependencies:
  - name: minio
    repository: "https://charts.bitnami.com/bitnami"
    version: 12.2.6
    condition: lokistack.minio.enabled
